ViewerBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
      layers:
        targetEntity: Layer
        joinTable:
          name: users_layers
          joinColumns:
            user_id:
              referencedColumnName: id
          inverseJoinColumns:
            layer_id:
              referencedColumnName: id
